# Dependencies
markdown:         redcarpet
pygments:         true
timezone:         Asia/Saigon

# Permalinks
permalink:        none

# Paginate
paginate:         5
paginate_path:    page-:num

# Setup
url:              'http://anhskohbo.github.io'
name:             'anhskohbo'
description:      'Nguyễn Văn Ánh BLOG'
author:           'Nguyễn Văn Ánh'