name:          anhskohbo
author:        Nguyễn Văn Ánh
description:   anhskohbo
url:           http://anhskohbo.github.io

timezone:      Asia/Saigon
markdown:      redcarpet
pygments:      true

permalink:     none
paginate:      5
paginate_path: page-:num

host:          localhost
port:          9000
exclude:       ['*.less']