name:          anhskohbo
description:   Blog of Anhskohbo
url:           http://http://anhskohbo.github.io

markdown:      redcarpet
pygments:      true
permalink:     none

paginate:      5
paginate_path: page-:num

host:          localhost
port:          9000